# Netlify deployment configuration for QuestForge
# This setup deploys the built Vite client (static assets) from the combined dist directory.
# Your Express API bundle (dist/index.js) will NOT run on Netlify as-is (Netlify serves static files only
# unless you convert endpoints to Netlify Functions / Edge Functions). If you later migrate the API, you can
# adjust the redirects section accordingly.

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # You can add external_node_modules if some deps should not be bundled
  # external_node_modules = ["some-big-lib"]

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

# SPA fallback so client-side routing works (wouter / React router style)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Add custom headers (example shown — commented out)
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Cache-Control = "public, max-age=0, must-revalidate"

# To enable a serverless API later:
# 1. Move/port each Express route to individual files under `netlify/functions/`.
# 2. Change the /api/* redirect target to `/.netlify/functions/:splat`.
# 3. Add a functions directory section:
# [functions]
#   directory = "netlify/functions"
#   node_bundler = "esbuild"